from pathlib import Path

p = Path('apps/web/src/pages/logger-page.ts')
s = p.read_text()
old_import = """import type {\n  GraphPaneGeometry,\n  GraphPaneSnapshot,\n  GraphWorkspaceLayout,\n  GraphWorkspaceSnapshot,\n  LoggerWorkspaceState,\n} from '../state/workspace-state';\n\nconst MAX_ACTIVE_WEB_TRACES = 8;\nconst GRAPH_PANE_IDS = ['pane-1', 'pane-2', 'pane-3', 'pane-4', 'pane-5', 'pane-6'] as const;\n\nfunction paneCountForLayout(layout: GraphWorkspaceLayout): number {\n  if (layout === 'grid4') return 4;\n  if (layout === 'grid5' || layout === 'freeform') return 5;\n  if (layout === 'grid6') return 6;\n  return 1;\n}\n\ntype FreeformArrange = 'mosaic' | 'columns' | 'rows' | 'cascade' | 'custom';\n\nfunction freeformArrangement(name: FreeformArrange): Record<string, GraphPaneGeometry> {\n  const rect = (x: number, y: number, width: number, height: number): GraphPaneGeometry =>\n    ({ x, y, width, height });\n\n  if (name === 'columns') {\n    return {\n      'pane-1': rect(0, 0, .57, .32),\n      'pane-2': rect(0, .34, .57, .32),\n      'pane-3': rect(0, .68, .57, .32),\n      'pane-4': rect(.59, 0, .41, .49),\n      'pane-5': rect(.59, .51, .41, .49),\n    };\n  }\n  if (name === 'rows') {\n    return {\n      'pane-1': rect(0, 0, 1, .19),\n      'pane-2': rect(0, .2025, 1, .19),\n      'pane-3': rect(0, .405, 1, .19),\n      'pane-4': rect(0, .6075, 1, .19),\n      'pane-5': rect(0, .81, 1, .19),\n    };\n  }\n  if (name === 'cascade') {\n    return {\n      'pane-1': rect(0, 0, .68, .58),\n      'pane-2': rect(.08, .08, .68, .58),\n      'pane-3': rect(.16, .16, .68, .58),\n      'pane-4': rect(.24, .24, .68, .58),\n      'pane-5': rect(.32, .32, .68, .58),\n    };\n  }\n  return {\n    'pane-1': rect(0, 0, .58, .56),\n    'pane-2': rect(.59, 0, .41, .275),\n    'pane-3': rect(.59, .285, .41, .275),\n    'pane-4': rect(0, .57, .49, .43),\n    'pane-5': rect(.50, .57, .50, .43),\n  };\n}\n\nfunction createEmptyPaneStates(): GraphPaneState[] {\n  return GRAPH_PANE_IDS.map((id) => ({ id, channelIds: [] }));\n}\n\nfunction normalizePaneStates(\n  panes: readonly GraphPaneSnapshot[] | undefined,\n  legacyChannelIds: readonly string[],\n): GraphPaneState[] {\n  const normalized = createEmptyPaneStates();\n  if (panes && panes.length > 0) {\n    for (const pane of panes.slice(0, GRAPH_PANE_IDS.length)) {\n      const target = normalized.find((candidate) => candidate.id === pane.id);\n      if (target) target.channelIds = [...pane.channelIds];\n    }\n  } else {\n    normalized[0]!.channelIds = [...legacyChannelIds];\n  }\n  return normalized;\n}\n\n"""
new_import = """import type {\n  GraphWorkspaceSnapshot,\n  LoggerWorkspaceState,\n} from '../state/workspace-state';\nimport {\n  GRAPH_PANE_IDS,\n  createEmptyPaneStates,\n  freeformArrangement,\n  normalizePaneStates,\n  paneCountForLayout,\n  type FreeformArrange,\n  type GraphPaneState,\n} from '../state/logger-pane-layout';\n\nconst MAX_ACTIVE_WEB_TRACES = 8;\n\n"""
if old_import not in s:
    raise SystemExit('top pane-layout block not found')
s = s.replace(old_import, new_import, 1)
old_type = """interface GraphPaneState {\n  id: string;\n  channelIds: string[];\n}\n\n"""
if old_type not in s:
    raise SystemExit('local GraphPaneState declaration not found')
s = s.replace(old_type, '', 1)
p.write_text(s)
