from pathlib import Path

path = Path('apps/web/src/pages/logger-page.ts')
text = path.read_text()
old = """      if (workspace.layout === 'freeform') {\n        const geometry = workspace.paneGeometry[runtime.id] ?? freeformArrangement('mosaic')[runtime.id]!;\n        if (maximized) {\n          runtime.windowElement.style.left = '0';\n          runtime.windowElement.style.top = '0';\n          runtime.windowElement.style.width = '100%';\n          runtime.windowElement.style.height = '100%';\n        } else {\n          runtime.windowElement.style.left = `${geometry.x * 100}%`;\n          runtime.windowElement.style.top = `${geometry.y * 100}%`;\n          runtime.windowElement.style.width = `${geometry.width * 100}%`;\n          runtime.windowElement.style.height = `${geometry.height * 100}%`;\n        }\n      } else {\n        runtime.windowElement.style.removeProperty('left');\n        runtime.windowElement.style.removeProperty('top');\n        runtime.windowElement.style.removeProperty('width');\n        runtime.windowElement.style.removeProperty('height');\n      }\n"""
new = """      if (workspace.layout === 'freeform' && inLayout) {\n        const geometry = workspace.paneGeometry[runtime.id] ?? freeformArrangement('mosaic')[runtime.id];\n        if (!geometry) {\n          runtime.windowElement.style.removeProperty('left');\n          runtime.windowElement.style.removeProperty('top');\n          runtime.windowElement.style.removeProperty('width');\n          runtime.windowElement.style.removeProperty('height');\n        } else if (maximized) {\n          runtime.windowElement.style.left = '0';\n          runtime.windowElement.style.top = '0';\n          runtime.windowElement.style.width = '100%';\n          runtime.windowElement.style.height = '100%';\n        } else {\n          runtime.windowElement.style.left = `${geometry.x * 100}%`;\n          runtime.windowElement.style.top = `${geometry.y * 100}%`;\n          runtime.windowElement.style.width = `${geometry.width * 100}%`;\n          runtime.windowElement.style.height = `${geometry.height * 100}%`;\n        }\n      } else {\n        runtime.windowElement.style.removeProperty('left');\n        runtime.windowElement.style.removeProperty('top');\n        runtime.windowElement.style.removeProperty('width');\n        runtime.windowElement.style.removeProperty('height');\n      }\n"""
if old not in text:
    raise SystemExit('freeform geometry block not found')
path.write_text(text.replace(old, new, 1))
