from pathlib import Path

path = Path('apps/web/src/pages/specialized-analyzer-suite-view.ts')
text = path.read_text()

text = text.replace(
"import { analyzerScopeBounds, populateAnalyzerScopeSelect, selectedAnalyzerScope } from './analyzer-scope';\n",
"import { analyzerScopeBounds, populateAnalyzerScopeSelect, selectedAnalyzerScope } from './analyzer-scope';\nimport { renderAlignedAnalyzerEvidence, type AnalyzerEvidenceSeries } from './analyzer-event-evidence';\n",
1)

text = text.replace(
"      <div class=\"specialized-analyzer-summary\"></div>\n      <section class=\"specialized-analyzer-events\">",
"      <div class=\"specialized-analyzer-summary\"></div>\n      <section class=\"specialized-analyzer-evidence\" hidden>\n        <header><div><strong data-specialized=\"evidence-title\">Event evidence</strong><span data-specialized=\"evidence-note\">Median with 10–90% envelope · t=0 at event onset</span></div><button type=\"button\" data-specialized=\"evidence-all\">All events</button></header>\n        <canvas class=\"specialized-analyzer-evidence-canvas\" aria-label=\"Analyzer event-aligned evidence graph\"></canvas>\n      </section>\n      <section class=\"specialized-analyzer-events\">",
1)

text = text.replace(
"  const summary = root.querySelector<HTMLElement>('.specialized-analyzer-summary');\n  const tableHead",
"  const summary = root.querySelector<HTMLElement>('.specialized-analyzer-summary');\n  const evidence = root.querySelector<HTMLElement>('.specialized-analyzer-evidence');\n  const evidenceCanvas = root.querySelector<HTMLCanvasElement>('.specialized-analyzer-evidence-canvas');\n  const evidenceAll = root.querySelector<HTMLButtonElement>('[data-specialized=\"evidence-all\"]');\n  const tableHead",
1)
text = text.replace(
"  if (!controls || !optionsGrid || !empty || !content || !summary || !tableHead || !tableBody) throw new Error('Specialized Analyzer suite structure is incomplete.');",
"  if (!controls || !optionsGrid || !empty || !content || !summary || !evidence || !evidenceCanvas || !evidenceAll || !tableHead || !tableBody) throw new Error('Specialized Analyzer suite structure is incomplete.');",
1)

anchor = "  interface EvidenceNavigation {\n"
insert = """  let restoreAllEvidence: (() => void) | undefined;\n\n  const finiteMean = (values: readonly (number | undefined)[]): number | undefined => {\n    const finite = values.filter((value): value is number => value !== undefined && Number.isFinite(value));\n    return finite.length ? finite.reduce((sum, value) => sum + value, 0) / finite.length : undefined;\n  };\n\n  const finiteMedian = (values: readonly (number | undefined)[]): number | undefined => {\n    const finite = values.filter((value): value is number => value !== undefined && Number.isFinite(value)).sort((a, b) => a - b);\n    if (!finite.length) return undefined;\n    const middle = Math.floor(finite.length / 2);\n    return finite.length % 2 ? finite[middle] : ((finite[middle - 1] ?? 0) + (finite[middle] ?? 0)) / 2;\n  };\n\n  const showAlignedEvidence = (\n    title: string,\n    series: readonly AnalyzerEvidenceSeries[],\n    events: readonly { startTimeMs: number; endTimeMs: number }[],\n    beforeMs: number,\n    afterMs: number,\n  ): void => {\n    evidence.hidden = events.length === 0 || series.length === 0;\n    if (evidence.hidden) { restoreAllEvidence = undefined; return; }\n    field('evidence-title').textContent = title;\n    field('evidence-note').textContent = `${events.length.toLocaleString()} event${events.length === 1 ? '' : 's'} · median + 10–90% envelope · t=0 onset`;\n    const renderAll = (): void => renderAlignedAnalyzerEvidence(evidenceCanvas, series, events, beforeMs, afterMs);\n    restoreAllEvidence = renderAll;\n    renderAll();\n  };\n\n  evidenceAll.addEventListener('click', () => restoreAllEvidence?.());\n\n"""
text = text.replace(anchor, insert + anchor, 1)

old_sig = """  const renderTable = (\n    title: string,\n    headers: readonly string[],\n    rows: readonly (readonly string[])[],\n    navigation: readonly EvidenceNavigation[] = [],\n  ): void => {"""
new_sig = """  const renderTable = (\n    title: string,\n    headers: readonly string[],\n    rows: readonly (readonly string[])[],\n    navigation: readonly EvidenceNavigation[] = [],\n    onSelect?: (index: number) => void,\n  ): void => {"""
text = text.replace(old_sig, new_sig, 1)

old_nav = """      if (target && context.openSamplesInLogger) {\n        tr.classList.add('specialized-analyzer-event-row--navigable');\n        tr.tabIndex = 0;\n        tr.title = 'Open this event in Logger';\n        const open = (): void => context.openSamplesInLogger?.(target);\n        tr.addEventListener('click', open);\n        tr.addEventListener('keydown', (event) => {\n          if (event.key === 'Enter' || event.key === ' ') {\n            event.preventDefault();\n            open();\n          }\n        });\n      }"""
new_nav = """      if (target) {\n        tr.classList.add('specialized-analyzer-event-row--navigable');\n        tr.tabIndex = 0;\n        tr.title = context.openSamplesInLogger ? 'Click to inspect · double-click or Enter to open in Logger' : 'Click to inspect';\n        const select = (): void => {\n          tableBody.querySelectorAll('tr').forEach((row) => row.classList.remove('specialized-analyzer-event-row--selected'));\n          tr.classList.add('specialized-analyzer-event-row--selected');\n          onSelect?.(index);\n        };\n        const open = (): void => context.openSamplesInLogger?.(target);\n        tr.addEventListener('click', select);\n        if (context.openSamplesInLogger) tr.addEventListener('dblclick', open);\n        tr.addEventListener('keydown', (event) => {\n          if (event.key === 'Enter' && context.openSamplesInLogger) { event.preventDefault(); open(); }\n          else if (event.key === ' ') { event.preventDefault(); select(); }\n        });\n      }"""
if old_nav not in text: raise SystemExit('navigation block not found')
text = text.replace(old_nav, new_nav, 1)

text = text.replace(
"    try {\n      if (domain === 'idle') {",
"    try {\n      evidence.hidden = true;\n      restoreAllEvidence = undefined;\n      if (domain === 'idle') {",
1)

old_idle_table = """        renderTable('Sag / recovery events', ['#', 'Start', 'End', 'Duration', 'Min error RPM', 'Recovery'], result.sagEvents.map((event, index) => [String(index + 1), timeText(event.startTimeMs), timeText(event.endTimeMs), `${event.durationMs.toFixed(0)} ms`, numberText(event.minimumErrorRpm), event.recoveryMs === undefined ? '—' : `${event.recoveryMs.toFixed(0)} ms`]), eventNavigation(result.sagEvents, 'Idle sag'));"""
new_idle_table = """        const idleSeries: AnalyzerEvidenceSeries[] = [\n          { label: 'RPM', range: rpm.range },\n          ...(target ? [{ label: 'Target', range: target.range }] : []),\n          ...(valve ? [{ label: 'Idle valve', range: valve.range }] : []),\n          ...(p ? [{ label: 'P term', range: p.range }] : []),\n          ...(i ? [{ label: 'I term', range: i.range }] : []),\n        ];\n        const idleAfterMs = Math.min(4000, Math.max(1200, ...result.sagEvents.map((event) => event.durationMs + (event.recoveryMs ?? 0) + 300)));\n        showAlignedEvidence('Idle sag / recovery · aligned evidence', idleSeries, result.sagEvents, 500, idleAfterMs);\n        renderSummary([\n          ['Scope', scoped.scope.label], ['Coverage', result.complete ? 'Complete' : 'Partial decoded'],\n          ['RPM mean', numberText(result.rpm.mean)], ['Target mean', numberText(result.target?.mean)],\n          ['Mean error', numberText(result.tracking?.meanError)], ['MAE', numberText(result.tracking?.meanAbsoluteError)],\n          ['Worst sag', numberText(result.sagEvents.length ? Math.min(...result.sagEvents.map((event) => event.minimumErrorRpm)) : undefined)],\n          ['Median recovery', result.sagEvents.length ? `${numberText(finiteMedian(result.sagEvents.map((event) => event.recoveryMs)), 0)} ms` : '—'],\n          ['Valve mean', numberText(result.valveDuty?.mean)], ['Bias mean', numberText(result.bias?.mean)],\n          ['Feed-forward mean', numberText(result.feedForward?.mean)], ['P / I / D mean', `${numberText(result.pTerm?.mean)} / ${numberText(result.iTerm?.mean)} / ${numberText(result.dTerm?.mean)}`],\n          ['Sag events', String(result.sagEvents.length)], ['Input samples', result.rpm.inputSampleCount.toLocaleString()],\n        ]);\n        renderTable('Sag / recovery events', ['#', 'Start', 'End', 'Duration', 'Min error RPM', 'Recovery'], result.sagEvents.map((event, index) => [String(index + 1), timeText(event.startTimeMs), timeText(event.endTimeMs), `${event.durationMs.toFixed(0)} ms`, numberText(event.minimumErrorRpm), event.recoveryMs === undefined ? '—' : `${event.recoveryMs.toFixed(0)} ms`]), eventNavigation(result.sagEvents, 'Idle sag'), (index) => {\n          const event = result.sagEvents[index];\n          if (event) { field('evidence-note').textContent = `Event ${index + 1} · ${event.minimumErrorRpm.toFixed(0)} RPM minimum error · t=0 onset`; renderAlignedAnalyzerEvidence(evidenceCanvas, idleSeries, [event], 500, idleAfterMs); }\n        });"""
if old_idle_table not in text: raise SystemExit('idle table line not found')
text = text.replace(old_idle_table, new_idle_table, 1)
# remove original idle renderSummary immediately before replacement, because new block includes richer summary
idle_start = text.find("        renderSummary([\n          ['Scope', scoped.scope.label]", text.find("if (domain === 'idle')"))
idle_end = text.find("        const idleSeries:", idle_start)
if idle_start >= 0 and idle_end > idle_start:
    text = text[:idle_start] + text[idle_end:]

old_ae_table = """        renderTable('Transient events', ['#', 'Type', 'Start', 'Duration', 'TPS Δ', 'MAP Δ', 'Predict error', 'AFR lean', 'AFR rich'], result.events.map((event, index) => [String(index + 1), event.direction, timeText(event.startTimeMs), `${event.durationMs.toFixed(0)} ms`, numberText(event.tpsDelta), numberText(event.mapDelta), numberText(event.predictionErrorAtEnd), numberText(event.afrLeanExcursion), numberText(event.afrRichExcursion)]), eventNavigation(result.events, 'AE / MAP transient'));"""
new_ae_table = """        const transientSeries: AnalyzerEvidenceSeries[] = [\n          { label: 'TPS', range: tps.range },\n          ...(map ? [{ label: 'MAP', range: map.range }] : []),\n          ...(predicted ? [{ label: 'Predicted MAP', range: predicted.range }] : []),\n          ...(afr ? [{ label: 'AFR', range: afr.range }] : []),\n        ];\n        const eventWindow = optionNumber('window', 500);\n        showAlignedEvidence('AE / MAP Predict · aligned transients', transientSeries, result.events, 200, Math.max(300, eventWindow));\n        renderSummary([\n          ['Scope', scoped.scope.label], ['Coverage', result.complete ? 'Complete' : 'Partial decoded'],\n          ['Events', String(result.events.length)], ['Tip-in / decel', `${tipIns} / ${result.events.length - tipIns}`],\n          ['TPS mean', numberText(result.tps.mean)], ['MAP mean', numberText(result.map?.mean)],\n          ['Predict error mean', numberText(finiteMean(result.events.map((event) => event.predictionErrorAtEnd)))],\n          ['Predict error MAE', numberText(finiteMean(result.events.map((event) => event.predictionErrorAtEnd === undefined ? undefined : Math.abs(event.predictionErrorAtEnd))))],\n          ['Peak lean excursion', numberText(result.events.length ? Math.max(...result.events.map((event) => event.afrLeanExcursion ?? 0)) : undefined)],\n          ['Peak rich excursion', numberText(result.events.length ? Math.min(...result.events.map((event) => event.afrRichExcursion ?? 0)) : undefined)],\n          ['Predicted MAP mean', numberText(result.predictedMap?.mean)], ['AFR mean', numberText(result.afr?.mean)],\n        ]);\n        renderTable('Transient events', ['#', 'Type', 'Start', 'Duration', 'TPS Δ', 'MAP Δ', 'Predict error', 'AFR lean', 'AFR rich'], result.events.map((event, index) => [String(index + 1), event.direction, timeText(event.startTimeMs), `${event.durationMs.toFixed(0)} ms`, numberText(event.tpsDelta), numberText(event.mapDelta), numberText(event.predictionErrorAtEnd), numberText(event.afrLeanExcursion), numberText(event.afrRichExcursion)]), eventNavigation(result.events, 'AE / MAP transient'), (index) => {\n          const event = result.events[index];\n          if (event) { field('evidence-note').textContent = `Event ${index + 1} · ${event.direction} · TPS Δ ${numberText(event.tpsDelta)} · t=0 onset`; renderAlignedAnalyzerEvidence(evidenceCanvas, transientSeries, [event], 200, Math.max(300, eventWindow)); }\n        });"""
if old_ae_table not in text: raise SystemExit('ae table line not found')
text = text.replace(old_ae_table, new_ae_table, 1)
# remove original ae summary directly before transient series
search_from = text.find("} else if (domain === 'ae-map')")
ae_start = text.find("        renderSummary([\n", search_from)
ae_end = text.find("        const transientSeries:", ae_start)
if ae_start >= 0 and ae_end > ae_start:
    text = text[:ae_start] + text[ae_end:]

path.write_text(text)

css = Path('apps/web/src/styles/specialized-analyzer.css')
css_text = css.read_text()
css_text += """\n\n.specialized-analyzer-evidence {\n  border: 1px solid #263b4c;\n  border-radius: 4px;\n  background: #071119;\n  overflow: hidden;\n}\n.specialized-analyzer-evidence[hidden] { display: none; }\n.specialized-analyzer-evidence > header {\n  display: flex; align-items: center; justify-content: space-between; gap: 10px;\n  padding: 6px 9px; border-bottom: 1px solid #203340; background: #0b171f;\n}\n.specialized-analyzer-evidence > header strong { display: block; color: #a6b8c3; font-size: 10px; }\n.specialized-analyzer-evidence > header span { display: block; margin-top: 2px; color: #6f8795; font-size: 8px; }\n.specialized-analyzer-evidence > header button { min-height: 24px; padding: 0 9px; border: 1px solid #2f4b59; border-radius: 3px; background: #101d28; color: #b7c8d1; font-size: 9px; }\n.specialized-analyzer-evidence-canvas { display: block; width: 100%; height: 250px; }\n.specialized-analyzer-event-row--selected td { background: #122838; color: #f0f7fb; }\n"""
css.write_text(css_text)
